apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-api
  template:
    metadata:
      labels:
        app: production-api
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: production-api
        image: mycontainerregistrytechchallenge.azurecr.io/production:latest
        ports:
        - containerPort: 8680
