apiVersion: v1
kind: Service
metadata:
  name: production-api
spec:
  selector:
    app: production-api
  ports:
    - name: http
      protocol: TCP
      port: 8680
      targetPort: 8680
  type: LoadBalancer
